<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Hitesh-Mac-Mini.local" name="com.eduven.testcase.ThirtyPercentTestCases" tests="3" failures="1" timestamp="31 Aug 2016 11:03:21 GMT" time="116.079" errors="0">
  <testcase name="currency_cconverter_test" time="28.715" classname="com.eduven.testcase.ThirtyPercentTestCases"/>
  <testcase name="stock_exchange_page_test" time="16.150" classname="com.eduven.testcase.ThirtyPercentTestCases">
    <failure type="java.lang.AssertionError" message="Error Message!!Text not found. expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Error Message!!Text not found. expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.eduven.modules.ThirtyPercent.verifyToastMessageForStockExchnage(ThirtyPercent.java:163)
	at com.eduven.testcase.ThirtyPercentTestCases.stock_exchange_page_test(ThirtyPercentTestCases.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:822)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1130)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:782)
	at org.testng.TestRunner.run(TestRunner.java:632)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1244)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
	at org.testng.TestNG.run(TestNG.java:1064)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:113)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:206)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:177)
]]>
    </failure>
  </testcase> <!-- stock_exchange_page_test -->
  <testcase name="verify_home_page_header_text_test" time="71.214" classname="com.eduven.testcase.ThirtyPercentTestCases"/>
</testsuite> <!-- com.eduven.testcase.ThirtyPercentTestCases -->
